ALTER TABLE MANAGER
ADD CONSTRAINT UQ_client_manager_name UNIQUE(name);

ALTER TABLE CLIENT
ADD CONSTRAINT UQ_login_name UNIQUE(login_name);

ALTER TABLE CLIENT
ADD CONSTRAINT UQ_email UNIQUE(email);

ALTER TABLE PRODUCT
ADD CONSTRAINT UQ_product_name UNIQUE(name);

ALTER TABLE CLIENT_PRODUCT
ADD CONSTRAINT UQ_client_id_product_id UNIQUE(client_id, product_id);
